### ISSUE TITLE
Can't run the code 

### ISSUE THREAD

**Issue by soufal** [fvmassoli/trj-based-adversarials-detection#2]
When i run the `python exctract_features_eval_class_representatives.py -ex -ma small`. 
Find out the error :
`FileNotFoundError: [Errno 2] No such file or directory: '../toy_models/mnist/model-smallcnn.pth'`.

But i can't find the pth file in the github?

Please help how can i find the file, thank you !

**Comment by fvmassoli** [comment]
We just uploaded the checkpoints.
You can find them here:
https://github.com/fvmassoli/trj-based-adversarials-detection/releases/tag/v1.0
